### ISSUE TITLE
Change Next/Previous Button Position

### ISSUE THREAD

**Issue by abhayhk2001** [abhayhk2001/DIET-Website#1]
The buttons should appear in the sides of the page rather than in the navbar.

**Comment by EdupugantiAkhil** [comment]
can you check out the new next and prev buttons 
i will change the svg later

**Comment by abhayhk2001** [comment]
If u have time make them appear on hover and add adding so they are a little inside the screen.
Yeah and then change the svg

**Comment by EdupugantiAkhil** [comment]
I added appear on hover for the previous chapter button so u can give recommendations before I do change it for the other one 

I can increase the width and height so tell me how u want it to look 

for mobile view, I can make it look completely different and keep both on the bottom right side as small circular buttons  or on a floating nav
