### ISSUE TITLE
Change Color of Navbar and Footer

### ISSUE THREAD

**Issue by abhayhk2001** [abhayhk2001/DIET-Website#2]
The colors are in [this](https://www.figma.com/file/8Hth84MFa9XaR5l9rqp2R7/AICTE-Website?node-id=0%3A1) figma design

**Comment by EdupugantiAkhil** [comment]
i updated them to rvce colours 
can look for an altranate colour for the active link in the navbar as it looks two bright?
i will increase the font size after switching to tailwind

**Comment by abhayhk2001** [comment]
Active link let it be white colour only 
a little bigger font size will be fine i think

**Comment by EdupugantiAkhil** [comment]
increased font size and changed it to rvce colors
