### ISSUE TITLE
Fix Display Issues When No Content Is Present

### ISSUE THREAD

**Issue by abhayhk2001** [abhayhk2001/DIET-Website#3]
Sometimes the page appears blank - [Class 2 -> EVS -> Chapter 1 -> Activity](https://rvce-diet-cwc.netlify.app/2/EVS/1/activity) .

Sometimes the page is filled with and empty `<div>` - [Class 3 -> MAT -> Chapter 2 -> Activity](https://rvce-diet-cwc.netlify.app/3/MAT/2/activity)

**Comment by EdupugantiAkhil** [comment]
in [Class 2 -> EVS -> Chapter 1 -> Activity](https://rvce-diet-cwc.netlify.app/2/EVS/1/activity)  the link is stored as
![image](https://user-images.githubusercontent.com/60013839/160269991-b112d9b2-8fe5-4c34-b601-c73a2a5386f9.png)

whare as in [Class 3 -> MAT -> Chapter 2 -> Activity](https://rvce-diet-cwc.netlify.app/3/MAT/2/activity)  the link is stored as 
![image](https://user-images.githubusercontent.com/60013839/160270033-233efccd-2d84-4ee8-a832-7b1fb80be3e9.png)
should I handle both the edge cases or would you mind removing the empty ones and i would make something that would show that its empty 

so keeping it as the 1st pic would be nice

**Comment by abhayhk2001** [comment]
Handle this edge case. 
![](https://user-images.githubusercontent.com/60013839/160269991-b112d9b2-8fe5-4c34-b601-c73a2a5386f9.png)

This one where there is a blank entry i will remove
![image](https://user-images.githubusercontent.com/57059990/160272730-f90b7354-b095-465f-ac08-64d7715c40ea.png)

**Comment by EdupugantiAkhil** [comment]
will now show this when no content is present 
![image](https://user-images.githubusercontent.com/60013839/160331159-3892ee2e-2fa5-47ee-bcd3-856828d0904c.png)
